name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest
    
    permissions:
      contents: write

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 10.8.0
          run_install: false

      - name: Install dependencies with updated lockfile
        run: pnpm install --no-frozen-lockfile

      - name: Compile TypeScript
        run: pnpm exec tsc

      - name: Build Electron app
        run: pnpm run build-only

      - name: Debug directory structure
        shell: pwsh
        run: |
          Write-Host "Current directory: $PWD"
          Write-Host "Checking for release files:"
          Get-ChildItem -Path ./release -Recurse | Select-Object FullName
      
      - name: Get version from package.json
        id: package_version
        shell: pwsh
        run: |
          $packageJson = Get-Content -Path package.json | ConvertFrom-Json
          $version = $packageJson.version
          echo "version=$version" >> $env:GITHUB_OUTPUT
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./release/*.exe
            ./release/*.yml
            ./release/*.yaml
            ./release/*.blockmap
          name: Release v${{ steps.package_version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}