name: Build and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest
    
    permissions:
      contents: write  # This is important for creating releases

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 10.8.0
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Compile TypeScript
        run: pnpm exec tsc

      - name: Build Electron app
        run: pnpm run build-only
        
      - name: Get version from package.json
        id: package_version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
        
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./release/Pegasus*.exe
            ./release/latest*.yml
          name: Release v${{ steps.package_version.outputs.current-version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}